<a href="https://colab.research.google.com/github/muminat58/dsrp_2026/blob/main/DSPR_2026_Muminat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/NCD_RisC_Nature_2020_Cholesterol_age_standardised_countries.csv')
df.head(15600)

,Country/Region/World,ISO,Sex,Year,Mean total cholesterol (mmol/L),Mean total cholesterol lower 95% uncertainty interval (mmol/L),Mean total cholesterol upper 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol (mmol/L),Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L),Mean HDL cholesterol (mmol/L),Mean HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)
0,Afghanistan,AFG,Men,1980,4.263545,3.539636,4.959936,2.919134,2.486837,3.339214,1.221839,0.926460,1.497237
1,Afghanistan,AFG,Men,1981,4.266327,3.569655,4.931141,2.934723,2.512884,3.344176,1.214738,0.932500,1.476955
2,Afghanistan,AFG,Men,1982,4.269252,3.612601,4.904159,2.950451,2.543536,3.345615,1.207716,0.935305,1.462378
3,Afghanistan,AFG,Men,1983,4.272437,3.646602,4.881011,2.966397,2.570361,3.353339,1.200752,0.943039,1.444552
4,Afghanistan,AFG,Men,1984,4.275822,3.673783,4.866126,2.982507,2.598309,3.360546,1.193839,0.947619,1.427836
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15595,Zimbabwe,ZWE,Women,2014,4.161298,3.755729,4.588048,2.945255,2.711719,3.174748,1.312036,1.140103,1.483028
15596,Zimbabwe,ZWE,Women,2015,4.157357,3.710967,4.625261,2.945829,2.704246,3.184318,1.310691,1.126460,1.491962
15597,Zimbabwe,ZWE,Women,2016,4.153718,3.661819,4.663383,2.946790,2.694693,3.195830,1.309282,1.110321,1.504699
15598,Zimbabwe,ZWE,Women,2017,4.150368,3.608575,4.709977,2.948084,2.683316,3.207449,1.307992,1.093114,1.517367
15599,Zimbabwe,ZWE,Women,2018,4.147003,3.544370,4.768410,2.949272,2.669244,3.222524,1.306701,1.077158,1.532687

In [ ]:
df.shape

(15600, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15600 entries, 0 to 15599
Data columns (total 13 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Country/Region/World                                              15600 non-null  object
 1   ISO                                                               15600 non-null  object
 2   Sex                                                               15600 non-null  object
 3   Year                                                              15600 non-null  int64
 4   Mean total cholesterol (mmol/L)                                   15600 non-null  float64
 5   Mean total cholesterol lower 95% uncertainty interval (mmol/L)    15600 non-null  float64
 6   Mean total cholesterol upper 95% uncertainty interval (mmol/L)    15600 non-null  float64
 7   Mean non-HDL cholesterol (mmol/L)                                 15600 non-null  float64
 8   Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L)  15600 non-null  float64
 9   Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L)  15600 non-null  float64
 10  Mean HDL cholesterol (mmol/L)                                     15600 non-null  float64
 11  Mean HDL cholesterol lower 95% uncertainty interval (mmol/L)      15600 non-null  float64
 12  Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)      15600 non-null  float64
dtypes: float64(9), int64(1), object(3)
memory usage: 1.5+ MB

In [ ]:
df.isna().sum()

Country/Region/World                                                0
ISO                                                                 0
Sex                                                                 0
Year                                                                0
Mean total cholesterol (mmol/L)                                     0
Mean total cholesterol lower 95% uncertainty interval (mmol/L)      0
Mean total cholesterol upper 95% uncertainty interval (mmol/L)      0
Mean non-HDL cholesterol (mmol/L)                                   0
Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L)    0
Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L)    0
Mean HDL cholesterol (mmol/L)                                       0
Mean HDL cholesterol lower 95% uncertainty interval (mmol/L)        0
Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)        0
dtype: int64

In [ ]:
df.dtypes

Country/Region/World                                                 object
ISO                                                                  object
Sex                                                                  object
Year                                                                  int64
Mean total cholesterol (mmol/L)                                     float64
Mean total cholesterol lower 95% uncertainty interval (mmol/L)      float64
Mean total cholesterol upper 95% uncertainty interval (mmol/L)      float64
Mean non-HDL cholesterol (mmol/L)                                   float64
Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L)    float64
Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L)    float64
Mean HDL cholesterol (mmol/L)                                       float64
Mean HDL cholesterol lower 95% uncertainty interval (mmol/L)        float64
Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)        float64
dtype: object

In [ ]:
df.describe()

,Year,Mean total cholesterol (mmol/L),Mean total cholesterol lower 95% uncertainty interval (mmol/L),Mean total cholesterol upper 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol (mmol/L),Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L),Mean HDL cholesterol (mmol/L),Mean HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)
count,15600.000000,15600.000000,15600.000000,15600.000000,15600.000000,15600.000000,15600.000000,15600.000000,15600.000000,15600.000000
mean,1999.000000,4.640884,4.267456,5.014135,3.409580,3.161987,3.656869,1.182812,1.011043,1.353301
std,11.254989,0.526163,0.593618,0.486433,0.541564,0.594014,0.498885,0.160172,0.194039,0.148257
min,1980.000000,3.420384,2.852869,3.688879,1.974066,1.482944,2.359677,0.707361,0.537585,0.852706
25%,1989.000000,4.233475,3.814052,4.641863,3.013087,2.730124,3.287278,1.071247,0.862170,1.256041
50%,1999.000000,4.631519,4.253378,5.002064,3.457274,3.223492,3.688262,1.146994,0.967051,1.338588
75%,2009.000000,4.977998,4.664222,5.305254,3.791976,3.578849,3.999924,1.267988,1.133620,1.430700
max,2018.000000,6.242019,5.981153,6.676697,5.080015,4.834224,5.341918,1.773267,1.700269,1.936919